#ifndef GFXDATA_UI_SIGN_H
#define GFXDATA_UI_SIGN_H

#define FRAME_UI_SIGN_SIGN1 0
#define FRAME_UI_SIGN_SIGN2 1
#define FRAME_UI_SIGN_SIGN3 2
#define FRAME_UI_SIGN_SIGN4 3
#define FRAME_UI_SIGN_SIGN5 4
#define FRAME_UI_SIGN_SIGN6 5

#endif // GFXDATA_UI_SIGN_H