#ifndef GFXDATA_WOODY_DOORLEFT_H
#define GFXDATA_WOODY_DOORLEFT_H

#define FRAME_WOODY_DOORLEFT_0 0
#define FRAME_WOODY_DOORLEFT_1 1
#define FRAME_WOODY_DOORLEFT_2 2
#define FRAME_WOODY_DOORLEFT_3 3
#define FRAME_WOODY_DOORLEFT_4 4
#define FRAME_WOODY_DOORLEFT_5 5
#define FRAME_WOODY_DOORLEFT_6 6
#define FRAME_WOODY_DOORLEFT_7 7
#define FRAME_WOODY_DOORLEFT_8 8
#define FRAME_WOODY_DOORLEFT_9 9
#define FRAME_WOODY_DOORLEFT_10 10
#define FRAME_WOODY_DOORLEFT_11 11
#define FRAME_WOODY_DOORLEFT_12 12
#define FRAME_WOODY_DOORLEFT_13 13
#define FRAME_WOODY_DOORLEFT_14 14
#define FRAME_WOODY_DOORLEFT_15 15
#define FRAME_WOODY_DOORLEFT_16 16
#define FRAME_WOODY_DOORLEFT_17 17
#define FRAME_WOODY_DOORLEFT_18 18
#define FRAME_WOODY_DOORLEFT_19 19
#define FRAME_WOODY_DOORLEFT_20 20
#define FRAME_WOODY_DOORLEFT_21 21
#define FRAME_WOODY_DOORLEFT_22 22
#define FRAME_WOODY_DOORLEFT_23 23
#define FRAME_WOODY_DOORLEFT_24 24

#endif // GFXDATA_WOODY_DOORLEFT_H