#ifndef GFXDATA_WOODY_DOORBACK_H
#define GFXDATA_WOODY_DOORBACK_H

#define FRAME_WOODY_DOORBACK_ENTER_0 0
#define FRAME_WOODY_DOORBACK_ENTER_1 1
#define FRAME_WOODY_DOORBACK_ENTER_2 2
#define FRAME_WOODY_DOORBACK_ENTER_3 3
#define FRAME_WOODY_DOORBACK_ENTER_4 4
#define FRAME_WOODY_DOORBACK_ENTER_5 5
#define FRAME_WOODY_DOORBACK_ENTER_6 6
#define FRAME_WOODY_DOORBACK_ENTER_7 7
#define FRAME_WOODY_DOORBACK_ENTER_8 8
#define FRAME_WOODY_DOORBACK_ENTER_9 9
#define FRAME_WOODY_DOORBACK_ENTER_10 10
#define FRAME_WOODY_DOORBACK_ENTER_11 11
#define FRAME_WOODY_DOORBACK_ENTER_12 12
#define FRAME_WOODY_DOORBACK_ENTER_13 13
#define FRAME_WOODY_DOORBACK_ENTER_14 14
#define FRAME_WOODY_DOORBACK_ENTER_15 15

#define FRAME_WOODY_DOORBACK_LEAVE_0 16
#define FRAME_WOODY_DOORBACK_LEAVE_1 17
#define FRAME_WOODY_DOORBACK_LEAVE_2 18
#define FRAME_WOODY_DOORBACK_LEAVE_3 19
#define FRAME_WOODY_DOORBACK_LEAVE_4 20
#define FRAME_WOODY_DOORBACK_LEAVE_5 21
#define FRAME_WOODY_DOORBACK_LEAVE_6 22
#define FRAME_WOODY_DOORBACK_LEAVE_7 23
#define FRAME_WOODY_DOORBACK_LEAVE_8 24
#define FRAME_WOODY_DOORBACK_LEAVE_9 25

#endif // GFXDATA_WOODY_DOORBACK_H