#ifndef ANIMATIONS_WOODY_DOORLEFT_H
#define ANIMATIONS_WOODY_DOORLEFT_H

#define ANIMATION_PACK_WOODY_DOORLEFT 1

#define ANIMATION_WOODY_DOORLEFT_ENTER 0
#define ANIMATION_WOODY_DOORLEFT_LEAVE 1

#endif // ANIMATIONS_WOODY_DOORLEFT_H