#ifndef ANIMATIONS_WOODY_DOORRIGHT_H
#define ANIMATIONS_WOODY_DOORRIGHT_H

#define ANIMATION_PACK_WOODY_DOORRIGHT 2

#define ANIMATION_WOODY_DOORRIGHT_ENTER 0
#define ANIMATION_WOODY_DOORRIGHT_LEAVE 1

#endif // ANIMATIONS_WOODY_DOORRIGHT_H