#ifndef ANIMATIONS_WOODY_DOORBACK_H
#define ANIMATIONS_WOODY_DOORBACK_H

#define ANIMATION_PACK_WOODY_DOORBACK 3

#define ANIMATION_WOODY_DOORBACK_ENTER 0
#define ANIMATION_WOODY_DOORBACK_LEAVE 1

#endif // ANIMATIONS_WOODY_DOORBACK_H