#ifndef ANIMATIONS_WOODY_GENERIC2_H
#define ANIMATIONS_WOODY_GENERIC2_H

#define ANIMATION_PACK_WOODY_GENERIC2 4

#define ANIMATION_WOODY_WARDROBE_ENTER 0
#define ANIMATION_WOODY_WARDROBE_LEAVE 1
#define ANIMATION_WOODY_OPEN 2
#define ANIMATION_WOODY_CLOSE 3
#define ANIMATION_WOODY_TAKE0 4
#define ANIMATION_WOODY_LOSE 5
#define ANIMATION_WOODY_TAKE_HIGH3 6
#define ANIMATION_WOODY_USE_MID 7
#define ANIMATION_WOODY_USE_MID_MICROWAVE 8

#endif // ANIMATIONS_WOODY_GENERIC2_H