#ifndef ANIMATIONS_WOODY_GENERIC_H
#define ANIMATIONS_WOODY_GENERIC_H

#define ANIMATION_PACK_WOODY_GENERIC 0

#define ANIMATION_WOODY_MS0 0
#define ANIMATION_WOODY_MS1 1
#define ANIMATION_WOODY_MS2 2
#define ANIMATION_WOODY_MS3 3
#define ANIMATION_WOODY_MG0 4
#define ANIMATION_WOODY_MG1 5
#define ANIMATION_WOODY_MG2 6
#define ANIMATION_WOODY_MG3 7
#define ANIMATION_WOODY_START 8
#define ANIMATION_WOODY_TRIUMPH 9

#endif // ANIMATIONS_WOODY_GENERIC_H