#ifndef ANIMATIONS_WOODY_GENERIC3_H
#define ANIMATIONS_WOODY_GENERIC3_H

#define ANIMATION_PACK_WOODY_GENERIC3 5

#define ANIMATION_WOODY_DECLINE 0
#define ANIMATION_WOODY_LAUGH 1
#define ANIMATION_WOODY_FEAR1 2
#define ANIMATION_WOODY_FEAR3 3
#define ANIMATION_WOODY_FEAR1_LOOP 4
#define ANIMATION_WOODY_FEAR3_LOOP 5

#endif // ANIMATIONS_WOODY_GENERIC3_H