#ifndef MUSIC_TYPES_H
#define MUSIC_TYPES_H

#define MUSIC_DNTRNK 0
#define MUSIC_TITEL 1
#define MUSIC_JINGLE_LEVELSTART 2
#define MUSIC_INGAME1_NORMAL 3
#define MUSIC_INGAME2_NORMAL 4
#define MUSIC_JINGLE_SUCCESS_NORMAL 5
#define MUSIC_JINGLE_FAILED 6

#endif // MUSIC_TYPES_H