#ifndef SFX_TYPES_H
#define SFX_TYPES_H

#define SOUND_NONE -1
#define SOUND_BUT1 0
#define SOUND_BUT_HOVER1 1
#define SOUND_DOOR_CLOSE1 2
#define SOUND_DOOR_OPEN1 3
#define SOUND_ILLEGAL 4
#define SOUND_LEVEL_START 5
#define SOUND_WOD_JUHU1 6
#define SOUND_WOD_LAUGH1 7
#define SOUND_WOD_STEP1A 8
#define SOUND_WOD_STEP2A 9
#define SOUND_OBJ_OPEN1 10
#define SOUND_OBJ_CLOSE1 11
#define SOUND_WOD_HA1 12
#define SOUND_GIVE_TAKE1 13
#define SOUND_GIVE_TAKE2 14
#define SOUND_WOD_EH1 15
#define SOUND_NA_USE1A 16
#define SOUND_NA_STEP1 17
#define SOUND_NA_STEP2 18
#define SOUND_NA_SITSDOWN1 19
#define SOUND_NA_REMOTE1 20
#define SOUND_NA_GETSUP1 21
#define SOUND_NA_PEEP1 22
#define SOUND_NA_PEEP2 23
#define SOUND_NA_PEEP3 24
#define SOUND_NA_PEEP4 25
#define SOUND_OBJ_SQUIEEK1 26
#define SOUND_NA_WORKOUT1 27
#define SOUND_NA_WORKOUT2 28
#define SOUND_NA_AAA_LONG2 30
#define SOUND_OBJ_PLOP1 30

#endif // SFX_TYPES_H