#ifndef ANIMATIONS_NEIGHBOUR_DOORLEFT_H
#define ANIMATIONS_NEIGHBOUR_DOORLEFT_H

#define ANIMATION_PACK_NEIGHBOUR_DOORLEFT 1

#define ANIMATION_NEIGHBOUR_DOORLEFT_ENTER 0
#define ANIMATION_NEIGHBOUR_DOORLEFT_LEAVE 1

#endif // ANIMATIONS_NEIGHBOUR_DOORLEFT_H