#ifndef ANIMATIONS_NEIGHBOUR_GAMEOVER_H
#define ANIMATIONS_NEIGHBOUR_GAMEOVER_H

#define ANIMATION_PACK_NEIGHBOUR_GAMEOVER 11

#define ANIMATION_NEIGHBOUR_KILL1 0
#define ANIMATION_NEIGHBOUR_KILL2 1
#define ANIMATION_NEIGHBOUR_KILL3 2

#endif // ANIMATIONS_NEIGHBOUR_GAMEOVER_H