#ifndef ANIMATIONS_NEIGHBOUR_GENERIC_H
#define ANIMATIONS_NEIGHBOUR_GENERIC_H

#define ANIMATION_PACK_NEIGHBOUR_GENERIC 0

#define ANIMATION_NEIGHBOUR_MS0 0
#define ANIMATION_NEIGHBOUR_MS1 1
#define ANIMATION_NEIGHBOUR_MS2 2
#define ANIMATION_NEIGHBOUR_MS3 3
#define ANIMATION_NEIGHBOUR_MG0 4
#define ANIMATION_NEIGHBOUR_MG1 5
#define ANIMATION_NEIGHBOUR_MG2 6
#define ANIMATION_NEIGHBOUR_MG3 7

#endif // ANIMATIONS_NEIGHBOUR_GENERIC_H