#ifndef ANIMATIONS_NEIGHBOUR_GENERIC3_H
#define ANIMATIONS_NEIGHBOUR_GENERIC3_H

#define ANIMATION_PACK_NEIGHBOUR_GENERIC3 7

#define ANIMATION_NEIGHBOUR_DOUBLETAKE1 0
#define ANIMATION_NEIGHBOUR_DISCOVER 1
#define ANIMATION_NEIGHBOUR_MR3 2
#define ANIMATION_NEIGHBOUR_USE_MID 3

#endif // ANIMATIONS_NEIGHBOUR_GENERIC3_H