#ifndef ANIMATIONS_NEIGHBOUR_GENERIC2_H
#define ANIMATIONS_NEIGHBOUR_GENERIC2_H

#define ANIMATION_PACK_NEIGHBOUR_GENERIC2 6

#define ANIMATION_NEIGHBOUR_SHOUT2 0
#define ANIMATION_NEIGHBOUR_SHOUT2_EXTRA 1

#endif // ANIMATIONS_NEIGHBOUR_GENERIC2_H