#ifndef ANIMATIONS_NEIGHBOUR_SOFA1_H
#define ANIMATIONS_NEIGHBOUR_SOFA1_H

#define ANIMATION_PACK_NEIGHBOUR_SOFA1 10

#define ANIMATION_NEIGHBOUR_SOFA1_NEIGHBOUR_SURPRISE 0

#endif // ANIMATIONS_NEIGHBOUR_SOFA1_H