#ifndef ANIMATIONS_NEIGHBOUR_SOFA_H
#define ANIMATIONS_NEIGHBOUR_SOFA_H

#define ANIMATION_PACK_NEIGHBOUR_SOFA 4

#define ANIMATION_NEIGHBOUR_SOFA_SIT_REMO 0
#define ANIMATION_NEIGHBOUR_SOFA_SIT 1
#define ANIMATION_NEIGHBOUR_SOFA_ENTER 2
#define ANIMATION_NEIGHBOUR_SOFA_LEAVE 3

#endif // ANIMATIONS_NEIGHBOUR_SOFA_H