#ifndef GFXDATA_NEIGHBOUR_BINOCULARS_H
#define GFXDATA_NEIGHBOUR_BINOCULARS_H

#define FRAME_NEIGHBOUR_PEEP_0 0
#define FRAME_NEIGHBOUR_PEEP_1 1
#define FRAME_NEIGHBOUR_PEEP_2 2
#define FRAME_NEIGHBOUR_PEEP_3 3
#define FRAME_NEIGHBOUR_PEEP_4 4
#define FRAME_NEIGHBOUR_PEEP_5 5
#define FRAME_NEIGHBOUR_PEEP_6 6
#define FRAME_NEIGHBOUR_PEEP_7 7
#define FRAME_NEIGHBOUR_PEEP_8 8
#define FRAME_NEIGHBOUR_PEEP_9 9
#define FRAME_NEIGHBOUR_PEEP_10 10
#define FRAME_NEIGHBOUR_PEEP_11 11
#define FRAME_NEIGHBOUR_PEEP_12 12
#define FRAME_NEIGHBOUR_PEEP_13 13
#define FRAME_NEIGHBOUR_PEEP_14 14
#define FRAME_NEIGHBOUR_PEEP_15 15
#define FRAME_NEIGHBOUR_PEEP_16 16
#define FRAME_NEIGHBOUR_PEEP_17 17
#define FRAME_NEIGHBOUR_PEEP_18 18
#define FRAME_NEIGHBOUR_PEEP_19 19
#define FRAME_NEIGHBOUR_PEEP_20 20
#define FRAME_NEIGHBOUR_PEEP_21 21
#define FRAME_NEIGHBOUR_PEEP_22 22
#define FRAME_NEIGHBOUR_PEEP_23 23
#define FRAME_NEIGHBOUR_PEEP_24 24
#define FRAME_NEIGHBOUR_PEEP_25 25
#define FRAME_NEIGHBOUR_PEEP_26 26
#define FRAME_NEIGHBOUR_PEEP_27 27
#define FRAME_NEIGHBOUR_PEEP_28 28
#define FRAME_NEIGHBOUR_PEEP_29 29
#define FRAME_NEIGHBOUR_PEEP_30 30
#define FRAME_NEIGHBOUR_PEEP_31 31
#define FRAME_NEIGHBOUR_PEEP_32 32
#define FRAME_NEIGHBOUR_PEEP_33 33
#define FRAME_NEIGHBOUR_PEEP_34 34
#define FRAME_NEIGHBOUR_PEEP_35 35
#define FRAME_NEIGHBOUR_PEEP_36 36
#define FRAME_NEIGHBOUR_PEEP_37 37
#define FRAME_NEIGHBOUR_PEEP_38 38
#define FRAME_NEIGHBOUR_PEEP_39 39
#define FRAME_NEIGHBOUR_PEEP_40 40

#define FRAME_NEIGHBOUR_PEEP_GLUE_31 41
#define FRAME_NEIGHBOUR_PEEP_GLUE_32 42
#define FRAME_NEIGHBOUR_PEEP_GLUE_33 43
#define FRAME_NEIGHBOUR_PEEP_GLUE_34 44
#define FRAME_NEIGHBOUR_PEEP_GLUE_35 45
#define FRAME_NEIGHBOUR_PEEP_GLUE_36 46
#define FRAME_NEIGHBOUR_PEEP_GLUE_37 47
#define FRAME_NEIGHBOUR_PEEP_GLUE_38 48
#define FRAME_NEIGHBOUR_PEEP_GLUE_39 49
#define FRAME_NEIGHBOUR_PEEP_GLUE_40 50

#endif // GFXDATA_NEIGHBOUR_BINOCULARS_H