#ifndef GFXDATA_NEIGHBOUR_DOORLEFT_H
#define GFXDATA_NEIGHBOUR_DOORLEFT_H

#define FRAME_NEIGHBOUR_DOORLEFT_0 0
#define FRAME_NEIGHBOUR_DOORLEFT_1 1
#define FRAME_NEIGHBOUR_DOORLEFT_2 2
#define FRAME_NEIGHBOUR_DOORLEFT_3 3
#define FRAME_NEIGHBOUR_DOORLEFT_4 4
#define FRAME_NEIGHBOUR_DOORLEFT_5 5
#define FRAME_NEIGHBOUR_DOORLEFT_6 6
#define FRAME_NEIGHBOUR_DOORLEFT_7 7
#define FRAME_NEIGHBOUR_DOORLEFT_8 8
#define FRAME_NEIGHBOUR_DOORLEFT_9 9
#define FRAME_NEIGHBOUR_DOORLEFT_10 10
#define FRAME_NEIGHBOUR_DOORLEFT_11 11
#define FRAME_NEIGHBOUR_DOORLEFT_12 12
#define FRAME_NEIGHBOUR_DOORLEFT_13 13
#define FRAME_NEIGHBOUR_DOORLEFT_14 14
#define FRAME_NEIGHBOUR_DOORLEFT_15 15
#define FRAME_NEIGHBOUR_DOORLEFT_16 16
#define FRAME_NEIGHBOUR_DOORLEFT_17 17
#define FRAME_NEIGHBOUR_DOORLEFT_18 18
#define FRAME_NEIGHBOUR_DOORLEFT_19 19

#endif // GFXDATA_NEIGHBOUR_DOORLEFT_H