#ifndef GFXDATA_NEIGHBOUR_DOORRIGHT_H
#define GFXDATA_NEIGHBOUR_DOORRIGHT_H

#define FRAME_NEIGHBOUR_DOORRIGHT_0 0
#define FRAME_NEIGHBOUR_DOORRIGHT_1 1
#define FRAME_NEIGHBOUR_DOORRIGHT_2 2
#define FRAME_NEIGHBOUR_DOORRIGHT_3 3
#define FRAME_NEIGHBOUR_DOORRIGHT_4 4
#define FRAME_NEIGHBOUR_DOORRIGHT_5 5
#define FRAME_NEIGHBOUR_DOORRIGHT_6 6
#define FRAME_NEIGHBOUR_DOORRIGHT_7 7
#define FRAME_NEIGHBOUR_DOORRIGHT_8 8
#define FRAME_NEIGHBOUR_DOORRIGHT_9 9
#define FRAME_NEIGHBOUR_DOORRIGHT_10 10
#define FRAME_NEIGHBOUR_DOORRIGHT_11 11
#define FRAME_NEIGHBOUR_DOORRIGHT_12 12
#define FRAME_NEIGHBOUR_DOORRIGHT_13 13
#define FRAME_NEIGHBOUR_DOORRIGHT_14 14
#define FRAME_NEIGHBOUR_DOORRIGHT_15 15
#define FRAME_NEIGHBOUR_DOORRIGHT_16 16
#define FRAME_NEIGHBOUR_DOORRIGHT_17 17
#define FRAME_NEIGHBOUR_DOORRIGHT_18 18
#define FRAME_NEIGHBOUR_DOORRIGHT_19 19

#endif // GFXDATA_NEIGHBOUR_DOORRIGHT_H