#ifndef GFXDATA_NEIGHBOUR_GAMEOVER_H
#define GFXDATA_NEIGHBOUR_GAMEOVER_H

#define FRAME_NEIGHBOUR_CLOUD_0 0
#define FRAME_NEIGHBOUR_CLOUD_1 1
#define FRAME_NEIGHBOUR_CLOUD_2 2
#define FRAME_NEIGHBOUR_CLOUD_3 3
#define FRAME_NEIGHBOUR_CLOUD_4 4

#define FRAME_NEIGHBOUR_KILLSHAKE_0 5
#define FRAME_NEIGHBOUR_KILLSHAKE_1 6
#define FRAME_NEIGHBOUR_KILLSHAKE_2 7
#define FRAME_NEIGHBOUR_KILLSHAKE_3 8
#define FRAME_NEIGHBOUR_KILLSHAKE_4 9
#define FRAME_NEIGHBOUR_KILLSHAKE_5 10

#define FRAME_NEIGHBOUR_PUNCH_0 11
#define FRAME_NEIGHBOUR_PUNCH_1 12
#define FRAME_NEIGHBOUR_PUNCH_2 13
#define FRAME_NEIGHBOUR_PUNCH_3 14
#define FRAME_NEIGHBOUR_PUNCH_4 15
#define FRAME_NEIGHBOUR_PUNCH_5 16
#define FRAME_NEIGHBOUR_PUNCH_6 17
#define FRAME_NEIGHBOUR_PUNCH_7 18
#define FRAME_NEIGHBOUR_PUNCH_8 19
#define FRAME_NEIGHBOUR_PUNCH_9 20
#define FRAME_NEIGHBOUR_PUNCH_10 21

#define FRAME_NEIGHBOUR_STOMP_0 22
#define FRAME_NEIGHBOUR_STOMP_1 23
#define FRAME_NEIGHBOUR_STOMP_2 24
#define FRAME_NEIGHBOUR_STOMP_3 25
#define FRAME_NEIGHBOUR_STOMP_4 26
#define FRAME_NEIGHBOUR_STOMP_5 27
#define FRAME_NEIGHBOUR_STOMP_6 28
#define FRAME_NEIGHBOUR_STOMP_7 29
#define FRAME_NEIGHBOUR_STOMP_8 30
#define FRAME_NEIGHBOUR_STOMP_9 31
#define FRAME_NEIGHBOUR_STOMP_10 32

#endif // GFXDATA_NEIGHBOUR_GAMEOVER_H