#ifndef GFXDATA_NEIGHBOUR_LOOK_H
#define GFXDATA_NEIGHBOUR_LOOK_H

#define FRAME_NEIGHBOUR_LOOK1_0 0
#define FRAME_NEIGHBOUR_LOOK1_1 1
#define FRAME_NEIGHBOUR_LOOK1_2 2
#define FRAME_NEIGHBOUR_LOOK1_3 3
#define FRAME_NEIGHBOUR_LOOK1_4 4
#define FRAME_NEIGHBOUR_LOOK1_5 5
#define FRAME_NEIGHBOUR_LOOK1_6 6
#define FRAME_NEIGHBOUR_LOOK1_7 7
#define FRAME_NEIGHBOUR_LOOK1_8 8

#endif // GFXDATA_NEIGHBOUR_LOOK_H