#ifndef GFXDATA_NEIGHBOUR_SOFA1_H
#define GFXDATA_NEIGHBOUR_SOFA1_H

#define FRAME_NEIGHBOUR_SIT_FART_6 0
#define FRAME_NEIGHBOUR_SIT_FART_7 1
#define FRAME_NEIGHBOUR_SIT_FART_8 2
#define FRAME_NEIGHBOUR_SIT_FART_9 3
#define FRAME_NEIGHBOUR_SIT_FART_10 4
#define FRAME_NEIGHBOUR_SIT_FART_11 5
#define FRAME_NEIGHBOUR_SIT_FART_12 8
#define FRAME_NEIGHBOUR_SIT_FART_13 9
#define FRAME_NEIGHBOUR_SIT_FART_14 10
#define FRAME_NEIGHBOUR_SIT_FART_15 11
#define FRAME_NEIGHBOUR_SIT_FART_16 12
#define FRAME_NEIGHBOUR_SIT_FART_17 13
#define FRAME_NEIGHBOUR_SIT_FART_18 14
#define FRAME_NEIGHBOUR_SIT_FART_19 15
#define FRAME_NEIGHBOUR_SIT_FART_20 16
#define FRAME_NEIGHBOUR_SIT_FART_21 17
#define FRAME_NEIGHBOUR_SIT_FART_22 18
#define FRAME_NEIGHBOUR_SIT_FART_23 19
#define FRAME_NEIGHBOUR_SIT_FART_24 20
#define FRAME_NEIGHBOUR_SIT_FART_25 21
#define FRAME_NEIGHBOUR_SIT_FART_26 22

#define FRAME_NEIGHBOUR_SIT_SURP_0 23
#define FRAME_NEIGHBOUR_SIT_SURP_1 24
#define FRAME_NEIGHBOUR_SIT_SURP_2 25
#define FRAME_NEIGHBOUR_SIT_SURP_3 26
#define FRAME_NEIGHBOUR_SIT_SURP_4 27
#define FRAME_NEIGHBOUR_SIT_SURP_5 28
#define FRAME_NEIGHBOUR_SIT_SURP_6 29

#endif // GFXDATA_NEIGHBOUR_SOFA1_H