#ifndef GFXDATA_NEIGHBOUR_SOFA_H
#define GFXDATA_NEIGHBOUR_SOFA_H

#define FRAME_NEIGHBOUR_SITDOWN_0 0
#define FRAME_NEIGHBOUR_SITDOWN_1 1
#define FRAME_NEIGHBOUR_SITDOWN_2 2
#define FRAME_NEIGHBOUR_SITDOWN_3 3
#define FRAME_NEIGHBOUR_SITDOWN_4 4
#define FRAME_NEIGHBOUR_SITDOWN_5 5

#define FRAME_NEIGHBOUR_SIT_1 6
#define FRAME_NEIGHBOUR_SIT_2 7

#define FRAME_NEIGHBOUR_SIT_REMO_0 8
#define FRAME_NEIGHBOUR_SIT_REMO_1 9
#define FRAME_NEIGHBOUR_SIT_REMO_2 10
#define FRAME_NEIGHBOUR_SIT_REMO_3 11
#define FRAME_NEIGHBOUR_SIT_REMO_4 12
#define FRAME_NEIGHBOUR_SIT_REMO_5 13
#define FRAME_NEIGHBOUR_SIT_REMO_6 14
#define FRAME_NEIGHBOUR_SIT_REMO_7 15
#define FRAME_NEIGHBOUR_SIT_REMO_8 16
#define FRAME_NEIGHBOUR_SIT_REMO_9 17
#define FRAME_NEIGHBOUR_SIT_REMO_10 18
#define FRAME_NEIGHBOUR_SIT_REMO_11 19
#define FRAME_NEIGHBOUR_SIT_REMO_12 20
#define FRAME_NEIGHBOUR_SIT_REMO_13 21

#endif // GFXDATA_NEIGHBOUR_SOFA_H