#ifndef GFXDATA_NEIGHBOUR_SOFA1_H
#define GFXDATA_NEIGHBOUR_SOFA1_H

#define FRAME_NEIGHBOUR_SIT_FART_6 0
#define FRAME_NEIGHBOUR_SIT_FART_7 1
#define FRAME_NEIGHBOUR_SIT_FART_8 2
#define FRAME_NEIGHBOUR_SIT_FART_9 3
#define FRAME_NEIGHBOUR_SIT_FART_10 4
#define FRAME_NEIGHBOUR_SIT_FART_11 5
#define FRAME_NEIGHBOUR_SIT_FART_12 6
#define FRAME_NEIGHBOUR_SIT_FART_13 7
#define FRAME_NEIGHBOUR_SIT_FART_14 8
#define FRAME_NEIGHBOUR_SIT_FART_15 9
#define FRAME_NEIGHBOUR_SIT_FART_16 10
#define FRAME_NEIGHBOUR_SIT_FART_17 11
#define FRAME_NEIGHBOUR_SIT_FART_18 12
#define FRAME_NEIGHBOUR_SIT_FART_19 13
#define FRAME_NEIGHBOUR_SIT_FART_20 14
#define FRAME_NEIGHBOUR_SIT_FART_21 15
#define FRAME_NEIGHBOUR_SIT_FART_22 16
#define FRAME_NEIGHBOUR_SIT_FART_23 17
#define FRAME_NEIGHBOUR_SIT_FART_24 18
#define FRAME_NEIGHBOUR_SIT_FART_25 19
#define FRAME_NEIGHBOUR_SIT_FART_26 20

#define FRAME_NEIGHBOUR_SIT_SURP_0 21
#define FRAME_NEIGHBOUR_SIT_SURP_1 22
#define FRAME_NEIGHBOUR_SIT_SURP_2 23
#define FRAME_NEIGHBOUR_SIT_SURP_3 24
#define FRAME_NEIGHBOUR_SIT_SURP_4 25
#define FRAME_NEIGHBOUR_SIT_SURP_5 26
#define FRAME_NEIGHBOUR_SIT_SURP_6 27

#endif // GFXDATA_NEIGHBOUR_SOFA1_H